blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('like/<slug:slug>', views.PostLike.as_view(), name='post_like'),
]

magazine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Post(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='blogpost_like', blank=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=500)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f'Comment {self.body} by {self.name}'

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from .models import Post
from .forms import CommentForm
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'


def post_detail(request, slug):
    template_name = 'post_detail.html'
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        liked = True

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            new_comment = comment_form.save(commit=False)

            new_comment.post = post

            new_comment.save()
    else:
        comment_form = CommentForm

    return render(request, template_name, {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'liked': liked

    })


class PostLike(View):

    def post(self, request, slug):
        post = get_object_or_404(Post, slug=slug)

        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

        return HttpResponseRedirect(reverse('post_detail', args=[slug]))

templates/add_post.html
{% extends 'base.html' %}
{% block content %}

<h1>Add blog post</h1>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/css/style.css">
    <title>Magazine</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Magazine</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Blog</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_signup' %}">SignUp</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
    {% block content %}

    {% endblock content %}
<footer>
    <div class="card text-center">
        <div class="card-header">
          Featured
        </div>
        <div class="card-body">
          <h5 class="card-title">Special title treatment</h5>
          <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
        <div class="card-footer text-muted">
          Copyright &copy; Magazine
        </div>
      </div>
</footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid hero">
  <h1>MAGAZINE</h1>
</div>
<hr>
<div class="container">
    {% for post in post_list %}
    <div class="post-container">
    <div class="blog-image"></div>
    <div class="card-body">
      <h2 class="card-title">{{ post.title }}</h2>
      <p class="card-text"><small class="text-muted">{{ post.author }} | {{ post.created_on }}</small></p>
      <a href="{% url 'post_detail' post.slug %}">LEARN MORE</a>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}

templates/post_detail.html
<script src="https://kit.fontawesome.com/215e1e67e2.js" crossorigin="anonymous"></script>
{% extends 'base.html' %}
{% block content %}
<div class="container post-container">
    <div class="blog-image"></div>
    <div class="card-body">
      <h2 class="card-title">{% block title %} {{ post.title }} {% endblock title %}</h2>
      <p class="card-text">{{ post.content | safe }}</p>
      <p class="card-text"><small class="text-muted">{{ post.author }} | {{ post.created_on }}</small></p>
    </div>

  </div>

  <div class="col-1">
    <strong>
      {% if user.is_authenticated %}
      <form class="d-inline" action="{% url 'post_like' post.slug %}" method="POST">
        {% csrf_token %}
        {% if liked %}
  
        <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="fa-solid fa-heart"></i></button>
        
        {% else %}
        <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="fa-regular fa-heart"></i></button>
        {% endif %}
      </form>
      {% else %}
      <a class="text-secondary" href="{% url 'account_login' %}">Login to like this post<i class="fa-regular fa-heart"></i></a>
      
      {% endif %}
      
      <span class="text-secondary"> {{ post.number_of_likes }} </span>
      
    </strong>
  </div>
  <div class="card">
    {% for comment in comments %}
    <div class="card-body">
      <h5 class="card-title">{{ comment.name }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">{{ comment.created_on }}</h6>
      <p class="card-text">{{ comment.body | linebreaks }}</p>
    </div>
    {% endfor %}
  </div>

<div class="card">
      {% if new_comment %}
      <div class="alert alert-success" role="alert">
        Your comment is awaiting moderation
      </div>
      {% else %}
      <h3>Leave a comment!</h3>
      <form method="POST" style="margin-top: 1.3em;">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-dark">Submit</button>
      </form>
      {% endif %}
    </div>
    
{% endblock content %}